package de.phash.semuxrpc;

public enum Action {
    ACCOUNTINFO, SHOW_ACCOUNTINFO, SHOW_TRANSFER, SHOW_VOTE, TRANSFER, SHOW_SIGN, SIGN, SHOW_ACC, CREATE_ACCOUNT, RECOVER_ACCOUNTS, CANCEL, OK, TRANSACTION_TYPE, VOTE, UNVOTE, SHOW_SEND, REFRESH
}
